[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "poseidon-solidity/=node_modules/poseidon-solidity/"
]
fs_permissions = [{ access = "read", path = "./test/data" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
